[plugin]
prepend_previewers = [
	# HEIC previewer
	{ mime = "image/heic", run = "heic" },
]

append_previewers = [
	# My fallback previewer
	{ name = "*", run = "binary" },
]

prepend_preloaders = [
	# HEIC preloader
	{ mime = "image/heic", run = "heic" },
]
